-- Readable views of game activity for the Supabase dashboard.
-- Open Table Editor -> submissions (one row per finished game) or daily_summary (one row per day).

-- Company names so views can show "Verizon" instead of "VZ". Refresh with scripts/build-sp500.py data if the list changes.
create table if not exists companies (
  symbol text primary key,
  name   text not null,
  sector text not null
);
alter table companies enable row level security;
insert into companies (symbol, name, sector) values
  ('NVDA', 'Nvidia', 'Information Technology'),
  ('AAPL', 'Apple Inc.', 'Information Technology'),
  ('GOOGL', 'Alphabet Inc.', 'Communication Services'),
  ('MSFT', 'Microsoft', 'Information Technology'),
  ('AMZN', 'Amazon', 'Consumer Discretionary'),
  ('META', 'Meta Platforms', 'Communication Services'),
  ('AVGO', 'Broadcom', 'Information Technology'),
  ('TSLA', 'Tesla, Inc.', 'Consumer Discretionary'),
  ('MU', 'Micron Technology', 'Information Technology'),
  ('BRK.B', 'Berkshire Hathaway', 'Financials'),
  ('LLY', 'Lilly (Eli)', 'Health Care'),
  ('AMD', 'Advanced Micro Devices', 'Information Technology'),
  ('JPM', 'JPMorgan Chase', 'Financials'),
  ('WMT', 'Walmart', 'Consumer Staples'),
  ('XOM', 'ExxonMobil', 'Energy'),
  ('V', 'Visa Inc.', 'Financials'),
  ('INTC', 'Intel', 'Information Technology'),
  ('JNJ', 'Johnson & Johnson', 'Health Care'),
  ('MA', 'Mastercard', 'Financials'),
  ('ABBV', 'AbbVie', 'Health Care'),
  ('PLTR', 'Palantir Technologies', 'Information Technology'),
  ('CSCO', 'Cisco', 'Information Technology'),
  ('LRCX', 'Lam Research', 'Information Technology'),
  ('AMAT', 'Applied Materials', 'Information Technology'),
  ('ORCL', 'Oracle Corporation', 'Information Technology'),
  ('CVX', 'Chevron Corporation', 'Energy'),
  ('COST', 'Costco', 'Consumer Staples'),
  ('CAT', 'Caterpillar Inc.', 'Industrials'),
  ('BAC', 'Bank of America', 'Financials'),
  ('KO', 'The Coca-Cola Company', 'Consumer Staples'),
  ('MRK', 'Merck & Co.', 'Health Care'),
  ('DELL', 'Dell Technologies', 'Information Technology'),
  ('PG', 'Procter & Gamble', 'Consumer Staples'),
  ('UNH', 'UnitedHealth Group', 'Health Care'),
  ('PANW', 'Palo Alto Networks', 'Information Technology'),
  ('GE', 'GE Aerospace', 'Industrials'),
  ('MS', 'Morgan Stanley', 'Financials'),
  ('PM', 'Philip Morris International', 'Consumer Staples'),
  ('NFLX', 'Netflix', 'Communication Services'),
  ('HD', 'The Home Depot', 'Consumer Discretionary'),
  ('CRWD', 'CrowdStrike', 'Information Technology'),
  ('GEV', 'GE Vernova', 'Industrials'),
  ('SNDK', 'Sandisk', 'Information Technology'),
  ('KLAC', 'KLA Corporation', 'Information Technology'),
  ('GS', 'Goldman Sachs', 'Financials'),
  ('ANET', 'Arista Networks', 'Information Technology'),
  ('TXN', 'Texas Instruments', 'Information Technology'),
  ('RTX', 'RTX Corporation', 'Industrials'),
  ('WFC', 'Wells Fargo', 'Financials'),
  ('TMO', 'Thermo Fisher Scientific', 'Health Care'),
  ('MRVL', 'Marvell Technology', 'Information Technology'),
  ('AMGN', 'Amgen', 'Health Care'),
  ('LIN', 'Linde plc', 'Materials'),
  ('STX', 'Seagate Technology', 'Information Technology'),
  ('C', 'Citigroup', 'Financials'),
  ('IBM', 'IBM', 'Information Technology'),
  ('APH', 'Amphenol', 'Information Technology'),
  ('AXP', 'American Express', 'Financials'),
  ('ADI', 'Analog Devices', 'Information Technology'),
  ('CRM', 'Salesforce', 'Information Technology'),
  ('QCOM', 'Qualcomm', 'Information Technology'),
  ('VZ', 'Verizon', 'Communication Services'),
  ('GILD', 'Gilead Sciences', 'Health Care'),
  ('DE', 'Deere & Company', 'Industrials'),
  ('DIS', 'The Walt Disney Company', 'Communication Services'),
  ('TMUS', 'T-Mobile US', 'Communication Services'),
  ('PEP', 'PepsiCo', 'Consumer Staples'),
  ('SCHW', 'Charles Schwab Corporation', 'Financials'),
  ('ETN', 'Eaton Corporation', 'Industrials'),
  ('ABT', 'Abbott Laboratories', 'Health Care'),
  ('WDC', 'Western Digital', 'Information Technology'),
  ('T', 'AT&T', 'Communication Services'),
  ('BLK', 'BlackRock', 'Financials'),
  ('MCD', 'McDonald''s', 'Consumer Discretionary'),
  ('WELL', 'Welltower', 'Real Estate'),
  ('UNP', 'Union Pacific Corporation', 'Industrials'),
  ('PFE', 'Pfizer', 'Health Care'),
  ('NEE', 'NextEra Energy', 'Utilities'),
  ('COP', 'ConocoPhillips', 'Energy'),
  ('BA', 'Boeing', 'Industrials'),
  ('DHR', 'Danaher Corporation', 'Health Care'),
  ('TJX', 'TJX Companies', 'Consumer Discretionary'),
  ('NOW', 'ServiceNow', 'Information Technology'),
  ('ISRG', 'Intuitive Surgical', 'Health Care'),
  ('ACN', 'Accenture', 'Information Technology'),
  ('UBER', 'Uber', 'Industrials'),
  ('GLW', 'Corning Inc.', 'Information Technology'),
  ('FTNT', 'Fortinet', 'Information Technology'),
  ('VRTX', 'Vertex Pharmaceuticals', 'Health Care'),
  ('CB', 'Chubb Limited', 'Financials'),
  ('BMY', 'Bristol Myers Squibb', 'Health Care'),
  ('MNST', 'Monster Beverage', 'Consumer Staples'),
  ('PGR', 'Progressive Corporation', 'Financials'),
  ('PH', 'Parker Hannifin', 'Industrials'),
  ('PLD', 'Prologis', 'Real Estate'),
  ('NEM', 'Newmont', 'Materials'),
  ('BKNG', 'Booking Holdings', 'Consumer Discretionary'),
  ('COF', 'Capital One', 'Financials'),
  ('MPC', 'Marathon Petroleum', 'Energy'),
  ('VLO', 'Valero Energy', 'Energy'),
  ('LMT', 'Lockheed Martin', 'Industrials'),
  ('SPGI', 'S&P Global', 'Financials'),
  ('MO', 'Altria', 'Consumer Staples'),
  ('MDT', 'Medtronic', 'Health Care'),
  ('CVS', 'CVS Health', 'Health Care'),
  ('SBUX', 'Starbucks', 'Consumer Discretionary'),
  ('PSX', 'Phillips 66', 'Energy'),
  ('MCK', 'McKesson Corporation', 'Health Care'),
  ('SYK', 'Stryker Corporation', 'Health Care'),
  ('ADP', 'Automatic Data Processing', 'Industrials'),
  ('LOW', 'Lowe''s', 'Consumer Discretionary'),
  ('TT', 'Trane Technologies', 'Industrials'),
  ('HOOD', 'Robinhood Markets', 'Financials'),
  ('EQIX', 'Equinix', 'Real Estate'),
  ('FCX', 'Freeport-McMoRan', 'Materials'),
  ('DDOG', 'Datadog', 'Information Technology'),
  ('BNY', 'BNY Mellon', 'Financials'),
  ('PWR', 'Quanta Services', 'Industrials'),
  ('CDNS', 'Cadence Design Systems', 'Information Technology'),
  ('ABNB', 'Airbnb', 'Consumer Discretionary'),
  ('SO', 'Southern Company', 'Utilities'),
  ('CME', 'CME Group', 'Financials'),
  ('VRT', 'Vertiv', 'Industrials'),
  ('APP', 'AppLovin', 'Communication Services'),
  ('SNPS', 'Synopsys', 'Information Technology'),
  ('ADBE', 'Adobe Inc.', 'Information Technology'),
  ('LITE', 'Lumentum', 'Information Technology'),
  ('MAR', 'Marriott International', 'Consumer Discretionary'),
  ('JCI', 'Johnson Controls', 'Industrials'),
  ('CEG', 'Constellation Energy', 'Utilities'),
  ('HCA', 'HCA Healthcare', 'Health Care'),
  ('HWM', 'Howmet Aerospace', 'Industrials'),
  ('GD', 'General Dynamics', 'Industrials'),
  ('USB', 'U.S. Bancorp', 'Financials'),
  ('DUK', 'Duke Energy', 'Utilities'),
  ('EMR', 'Emerson Electric', 'Industrials'),
  ('PNC', 'PNC Financial Services', 'Financials'),
  ('CSX', 'CSX Corporation', 'Industrials'),
  ('HPE', 'Hewlett Packard Enterprise', 'Information Technology'),
  ('ICE', 'Intercontinental Exchange', 'Financials'),
  ('WMB', 'Williams Companies', 'Energy'),
  ('BX', 'Blackstone Inc.', 'Financials'),
  ('MMM', '3M', 'Industrials'),
  ('ELV', 'Elevance Health', 'Health Care'),
  ('MRSH', 'Marsh McLennan', 'Financials'),
  ('KKR', 'KKR & Co.', 'Financials'),
  ('BE', 'Bloom Energy', 'Industrials'),
  ('WM', 'Waste Management', 'Industrials'),
  ('UPS', 'United Parcel Service', 'Industrials'),
  ('DASH', 'DoorDash', 'Consumer Discretionary'),
  ('CTAS', 'Cintas', 'Industrials'),
  ('SHW', 'Sherwin-Williams', 'Materials'),
  ('WBD', 'Warner Bros. Discovery', 'Communication Services'),
  ('MCO', 'Moody''s Corporation', 'Financials'),
  ('CMCSA', 'Comcast', 'Communication Services'),
  ('ECL', 'Ecolab', 'Materials'),
  ('REGN', 'Regeneron Pharmaceuticals', 'Health Care'),
  ('INTU', 'Intuit', 'Information Technology'),
  ('MRNA', 'Moderna', 'Health Care'),
  ('TRV', 'The Travelers Companies', 'Financials'),
  ('AMT', 'American Tower', 'Real Estate'),
  ('ROST', 'Ross Stores', 'Consumer Discretionary'),
  ('ITW', 'Illinois Tool Works', 'Industrials'),
  ('MSI', 'Motorola Solutions', 'Information Technology'),
  ('EOG', 'EOG Resources', 'Energy'),
  ('MDLZ', 'Mondelez International', 'Consumer Staples'),
  ('SLB', 'Schlumberger', 'Energy'),
  ('RCL', 'Royal Caribbean Group', 'Consumer Discretionary'),
  ('TGT', 'Target Corporation', 'Consumer Staples'),
  ('CMI', 'Cummins', 'Industrials'),
  ('HLT', 'Hilton Worldwide', 'Consumer Discretionary'),
  ('CI', 'Cigna', 'Health Care'),
  ('NSC', 'Norfolk Southern', 'Industrials'),
  ('GM', 'General Motors', 'Consumer Discretionary'),
  ('CVNA', 'Carvana', 'Consumer Discretionary'),
  ('ORLY', 'O''Reilly Automotive', 'Consumer Discretionary'),
  ('NOC', 'Northrop Grumman', 'Industrials'),
  ('KMI', 'Kinder Morgan', 'Energy'),
  ('FDX', 'FedEx', 'Industrials'),
  ('HON', 'Honeywell Technologies', 'Industrials'),
  ('APO', 'Apollo Global Management', 'Financials'),
  ('CL', 'Colgate-Palmolive', 'Consumer Staples'),
  ('MPWR', 'Monolithic Power Systems', 'Information Technology'),
  ('DLR', 'Digital Realty', 'Real Estate'),
  ('AEP', 'American Electric Power', 'Utilities'),
  ('TER', 'Teradyne', 'Information Technology'),
  ('SPG', 'Simon Property Group', 'Real Estate'),
  ('URI', 'United Rentals', 'Industrials'),
  ('KEYS', 'Keysight Technologies', 'Information Technology'),
  ('RSG', 'Republic Services', 'Industrials'),
  ('TEL', 'TE Connectivity', 'Information Technology'),
  ('BSX', 'Boston Scientific', 'Health Care'),
  ('COHR', 'Coherent Corp.', 'Information Technology'),
  ('APD', 'Air Products', 'Materials'),
  ('TDG', 'TransDigm Group', 'Industrials'),
  ('GWW', 'W. W. Grainger', 'Industrials'),
  ('NXPI', 'NXP Semiconductors', 'Information Technology'),
  ('MET', 'MetLife', 'Financials'),
  ('TRGP', 'Targa Resources', 'Energy'),
  ('AJG', 'Arthur J. Gallagher & Co.', 'Financials'),
  ('FIX', 'Comfort Systems USA', 'Industrials'),
  ('COR', 'Cencora', 'Health Care'),
  ('AON', 'Aon plc', 'Financials'),
  ('PCAR', 'Paccar', 'Industrials'),
  ('OXY', 'Occidental Petroleum', 'Energy'),
  ('FAST', 'Fastenal', 'Industrials'),
  ('AME', 'Ametek', 'Industrials'),
  ('ALL', 'Allstate', 'Financials'),
  ('TFC', 'Truist Financial', 'Financials'),
  ('AFL', 'Aflac', 'Financials'),
  ('DAL', 'Delta Air Lines', 'Industrials'),
  ('BKR', 'Baker Hughes', 'Energy'),
  ('OKE', 'Oneok', 'Energy'),
  ('CRH', 'CRH plc', 'Materials'),
  ('GRMN', 'Garmin', 'Consumer Discretionary'),
  ('CIEN', 'Ciena', 'Information Technology'),
  ('NUE', 'Nucor', 'Materials'),
  ('D', 'Dominion Energy', 'Utilities'),
  ('CAH', 'Cardinal Health', 'Health Care'),
  ('NKE', 'Nike, Inc.', 'Consumer Discretionary'),
  ('FANG', 'Diamondback Energy', 'Energy'),
  ('DVN', 'Devon Energy', 'Energy'),
  ('NDAQ', 'Nasdaq, Inc.', 'Financials'),
  ('SRE', 'Sempra', 'Utilities'),
  ('O', 'Realty Income', 'Real Estate'),
  ('COIN', 'Coinbase', 'Financials'),
  ('PSA', 'Public Storage', 'Real Estate'),
  ('ROK', 'Rockwell Automation', 'Industrials'),
  ('EW', 'Edwards Lifesciences', 'Health Care'),
  ('HONA', 'Honeywell Aerospace', 'Industrials'),
  ('WAB', 'Wabtec', 'Industrials'),
  ('BDX', 'Becton Dickinson', 'Health Care'),
  ('F', 'Ford Motor Company', 'Consumer Discretionary'),
  ('STT', 'State Street Corporation', 'Financials'),
  ('VMRK', 'Vivmark Residential', 'Real Estate'),
  ('EBAY', 'eBay Inc.', 'Consumer Discretionary'),
  ('A', 'Agilent Technologies', 'Health Care'),
  ('VST', 'Vistra Corp.', 'Utilities'),
  ('ETR', 'Entergy', 'Utilities'),
  ('AZO', 'AutoZone', 'Consumer Discretionary'),
  ('FITB', 'Fifth Third Bancorp', 'Financials'),
  ('VEEV', 'Veeva Systems', 'Health Care'),
  ('HUM', 'Humana', 'Health Care'),
  ('CARR', 'Carrier Global', 'Industrials'),
  ('PYPL', 'PayPal', 'Financials'),
  ('WDAY', 'Workday, Inc.', 'Information Technology'),
  ('P', 'Everpure', 'Information Technology'),
  ('AMP', 'Ameriprise Financial', 'Financials'),
  ('XYZ', 'Block, Inc.', 'Financials'),
  ('LHX', 'L3Harris', 'Industrials'),
  ('ADSK', 'Autodesk', 'Information Technology'),
  ('XEL', 'Xcel Energy', 'Utilities'),
  ('VTR', 'Ventas', 'Real Estate'),
  ('IQV', 'IQVIA', 'Health Care'),
  ('FERG', 'Ferguson Enterprises', 'Industrials'),
  ('MCHP', 'Microchip Technology', 'Information Technology'),
  ('NTAP', 'NetApp', 'Information Technology'),
  ('WAT', 'Waters Corporation', 'Health Care'),
  ('EXC', 'Exelon', 'Utilities'),
  ('KDP', 'Keurig Dr Pepper', 'Consumer Staples'),
  ('FLEX', 'Flex Ltd.', 'Information Technology'),
  ('CMG', 'Chipotle Mexican Grill', 'Consumer Discretionary'),
  ('IDXX', 'Idexx Laboratories', 'Health Care'),
  ('ILMN', 'Illumina, Inc.', 'Health Care'),
  ('MSCI', 'MSCI', 'Financials'),
  ('AIG', 'American International Group', 'Financials'),
  ('LYV', 'Live Nation Entertainment', 'Communication Services'),
  ('PRU', 'Prudential Financial', 'Financials'),
  ('IBKR', 'Interactive Brokers', 'Financials'),
  ('ARES', 'Ares Management', 'Financials'),
  ('DHI', 'D. R. Horton', 'Consumer Discretionary'),
  ('ADM', 'Archer Daniels Midland', 'Consumer Staples'),
  ('ED', 'Consolidated Edison', 'Utilities'),
  ('SYY', 'Sysco', 'Consumer Staples'),
  ('TTWO', 'Take-Two Interactive', 'Communication Services'),
  ('CBRE', 'CBRE Group', 'Real Estate'),
  ('YUM', 'Yum! Brands', 'Consumer Discretionary'),
  ('ODFL', 'Old Dominion', 'Industrials'),
  ('UAL', 'United Airlines Holdings', 'Industrials'),
  ('PAYX', 'Paychex', 'Industrials'),
  ('ROP', 'Roper Technologies', 'Information Technology'),
  ('KR', 'Kroger', 'Consumer Staples'),
  ('AXON', 'Axon Enterprise', 'Industrials'),
  ('HIG', 'The Hartford', 'Financials'),
  ('EME', 'Emcor', 'Industrials'),
  ('PEG', 'Public Service Enterprise Group', 'Utilities'),
  ('CCL', 'Carnival Corporation', 'Consumer Discretionary'),
  ('TKO', 'TKO Group Holdings', 'Communication Services'),
  ('WEC', 'WEC Energy Group', 'Utilities'),
  ('IRM', 'Iron Mountain', 'Real Estate'),
  ('KVUE', 'Kenvue', 'Consumer Staples'),
  ('BIIB', 'Biogen', 'Health Care'),
  ('EL', 'The Estée Lauder Companies', 'Consumer Staples'),
  ('PCG', 'PG&E Corporation', 'Utilities'),
  ('DXCM', 'Dexcom', 'Health Care'),
  ('STLD', 'Steel Dynamics', 'Materials'),
  ('ACGL', 'Arch Capital Group', 'Financials'),
  ('HSY', 'The Hershey Company', 'Consumer Staples'),
  ('RMD', 'ResMed', 'Health Care'),
  ('VMC', 'Vulcan Materials Company', 'Materials'),
  ('JBL', 'Jabil', 'Information Technology'),
  ('MTB', 'M&T Bank', 'Financials'),
  ('KMB', 'Kimberly-Clark', 'Consumer Staples'),
  ('EQT', 'EQT Corporation', 'Energy'),
  ('ON', 'ON Semiconductor', 'Information Technology'),
  ('CBOE', 'Cboe Global Markets', 'Financials'),
  ('NTRS', 'Northern Trust', 'Financials'),
  ('RJF', 'Raymond James Financial', 'Financials'),
  ('HBAN', 'Huntington Bancshares', 'Financials'),
  ('CNC', 'Centene Corporation', 'Health Care'),
  ('EXPE', 'Expedia Group', 'Consumer Discretionary'),
  ('MTD', 'Mettler Toledo', 'Health Care'),
  ('IR', 'Ingersoll Rand', 'Industrials'),
  ('HPQ', 'HP Inc.', 'Information Technology'),
  ('GEHC', 'GE HealthCare', 'Health Care'),
  ('MLM', 'Martin Marietta Materials', 'Materials'),
  ('RDDT', 'Reddit', 'Communication Services'),
  ('ZTS', 'Zoetis', 'Health Care'),
  ('TDY', 'Teledyne Technologies', 'Information Technology'),
  ('CCI', 'Crown Castle', 'Real Estate'),
  ('EXR', 'Extra Space Storage', 'Real Estate'),
  ('AEE', 'Ameren', 'Utilities'),
  ('SMCI', 'Supermicro', 'Information Technology'),
  ('WSM', 'Williams-Sonoma, Inc.', 'Consumer Discretionary'),
  ('CTSH', 'Cognizant', 'Information Technology'),
  ('WTW', 'Willis Towers Watson', 'Financials'),
  ('Q', 'Qnity Electronics', 'Information Technology'),
  ('CFG', 'Citizens Financial Group', 'Financials'),
  ('KHC', 'Kraft Heinz', 'Consumer Staples'),
  ('SYF', 'Synchrony Financial', 'Financials'),
  ('HAL', 'Halliburton', 'Energy'),
  ('ATO', 'Atmos Energy', 'Utilities'),
  ('DG', 'Dollar General', 'Consumer Staples'),
  ('VRSN', 'Verisign', 'Information Technology'),
  ('FOXA', 'Fox Corporation', 'Communication Services'),
  ('WST', 'West Pharmaceutical Services', 'Health Care'),
  ('ECHO', 'EchoStar', 'Communication Services'),
  ('DTE', 'DTE Energy', 'Utilities'),
  ('CPAY', 'Corpay', 'Financials'),
  ('WRB', 'W. R. Berkley Corporation', 'Financials'),
  ('DGX', 'Quest Diagnostics', 'Health Care'),
  ('AWK', 'American Water Works', 'Utilities'),
  ('DOV', 'Dover Corporation', 'Industrials'),
  ('CPRT', 'Copart', 'Industrials'),
  ('FFIV', 'F5, Inc.', 'Information Technology'),
  ('FE', 'FirstEnergy', 'Utilities'),
  ('VICI', 'Vici Properties', 'Real Estate'),
  ('CINF', 'Cincinnati Financial', 'Financials'),
  ('LH', 'Labcorp', 'Health Care'),
  ('HUBB', 'Hubbell Incorporated', 'Industrials'),
  ('PPL', 'PPL Corporation', 'Utilities'),
  ('OTIS', 'Otis Worldwide', 'Industrials'),
  ('CNP', 'CenterPoint Energy', 'Utilities'),
  ('EXPD', 'Expeditors International', 'Industrials'),
  ('ES', 'Eversource Energy', 'Utilities'),
  ('FISV', 'Fiserv', 'Financials'),
  ('PFG', 'Principal Financial Group', 'Financials'),
  ('TPR', 'Tapestry, Inc.', 'Consumer Discretionary'),
  ('LVS', 'Las Vegas Sands', 'Consumer Discretionary'),
  ('INCY', 'Incyte', 'Health Care'),
  ('XYL', 'Xylem Inc.', 'Industrials'),
  ('PPG', 'PPG Industries', 'Materials'),
  ('TPL', 'Texas Pacific Land Corporation', 'Energy'),
  ('VLTO', 'Veralto', 'Industrials'),
  ('ULTA', 'Ulta Beauty', 'Consumer Discretionary'),
  ('RF', 'Regions Financial Corporation', 'Financials'),
  ('CASY', 'Casey''s', 'Consumer Staples'),
  ('SW', 'Smurfit Westrock', 'Materials'),
  ('TROW', 'T. Rowe Price', 'Financials'),
  ('DRI', 'Darden Restaurants', 'Consumer Discretionary'),
  ('CHD', 'Church & Dwight', 'Consumer Staples'),
  ('VRSK', 'Verisk Analytics', 'Industrials'),
  ('PHM', 'PulteGroup', 'Consumer Discretionary'),
  ('RL', 'Ralph Lauren Corporation', 'Consumer Discretionary'),
  ('L', 'Loews Corporation', 'Financials'),
  ('DLTR', 'Dollar Tree', 'Consumer Staples'),
  ('KEY', 'KeyCorp', 'Financials'),
  ('JBHT', 'J.B. Hunt', 'Industrials'),
  ('GPN', 'Global Payments', 'Financials'),
  ('IFF', 'International Flavors & Fragrances', 'Materials'),
  ('EIX', 'Edison International', 'Utilities'),
  ('BRO', 'Brown & Brown', 'Financials'),
  ('OMC', 'Omnicom Group', 'Communication Services'),
  ('BG', 'Bunge Global', 'Consumer Staples'),
  ('LUV', 'Southwest Airlines', 'Industrials'),
  ('PKG', 'Packaging Corporation of America', 'Materials'),
  ('STE', 'Steris', 'Health Care'),
  ('NRG', 'NRG Energy', 'Utilities'),
  ('VTRS', 'Viatris', 'Health Care'),
  ('CMS', 'CMS Energy', 'Utilities'),
  ('DOW', 'Dow Inc.', 'Materials'),
  ('EXE', 'Expand Energy', 'Energy'),
  ('LEN', 'Lennar', 'Consumer Discretionary'),
  ('AMCR', 'Amcor', 'Materials'),
  ('STZ', 'Constellation Brands', 'Consumer Staples'),
  ('SNA', 'Snap-on', 'Industrials'),
  ('NI', 'NiSource', 'Utilities'),
  ('LYB', 'LyondellBasell', 'Materials'),
  ('FSLR', 'First Solar', 'Information Technology'),
  ('BBY', 'Best Buy', 'Consumer Discretionary'),
  ('NDSN', 'Nordson Corporation', 'Industrials'),
  ('BR', 'Broadridge Financial Solutions', 'Industrials'),
  ('EVRG', 'Evergy', 'Utilities'),
  ('CHRW', 'C.H. Robinson', 'Industrials'),
  ('ZBRA', 'Zebra Technologies', 'Information Technology'),
  ('TSN', 'Tyson Foods', 'Consumer Staples'),
  ('DD', 'DuPont', 'Industrials'),
  ('CF', 'CF Industries', 'Materials'),
  ('ESS', 'Essex Property Trust', 'Real Estate'),
  ('GPC', 'Genuine Parts Company', 'Consumer Discretionary'),
  ('IP', 'International Paper', 'Materials'),
  ('FIS', 'Fidelity National Information Services', 'Financials'),
  ('CDW', 'CDW Corporation', 'Information Technology'),
  ('IEX', 'IDEX Corporation', 'Industrials'),
  ('GIS', 'General Mills', 'Consumer Staples'),
  ('FTV', 'Fortive', 'Industrials'),
  ('ZBH', 'Zimmer Biomet', 'Health Care'),
  ('SBAC', 'SBA Communications', 'Real Estate'),
  ('RVTY', 'Revvity', 'Health Care'),
  ('FDXF', 'FedEx Freight', 'Industrials'),
  ('TSCO', 'Tractor Supply', 'Consumer Discretionary'),
  ('LNT', 'Alliant Energy', 'Utilities'),
  ('BEN', 'Franklin Resources', 'Financials'),
  ('EFX', 'Equifax', 'Industrials'),
  ('J', 'Jacobs Solutions', 'Industrials'),
  ('NVR', 'NVR, Inc.', 'Consumer Discretionary'),
  ('PTC', 'PTC Inc.', 'Information Technology'),
  ('INVH', 'Invitation Homes', 'Real Estate'),
  ('NWSA', 'News Corp', 'Communication Services'),
  ('HST', 'Host Hotels & Resorts', 'Real Estate'),
  ('AKAM', 'Akamai Technologies', 'Information Technology'),
  ('LDOS', 'Leidos', 'Industrials'),
  ('APA', 'APA Corporation', 'Energy'),
  ('BALL', 'Ball Corporation', 'Materials'),
  ('SOLV', 'Solventum', 'Health Care'),
  ('KIM', 'Kimco Realty', 'Real Estate'),
  ('ROL', 'Rollins, Inc.', 'Industrials'),
  ('FICO', 'Fair Isaac', 'Information Technology'),
  ('EG', 'Everest Group', 'Financials'),
  ('CRL', 'Charles River Laboratories', 'Health Care'),
  ('SWK', 'Stanley Black & Decker', 'Industrials'),
  ('TYL', 'Tyler Technologies', 'Information Technology'),
  ('MAA', 'Mid-America Apartment Communities', 'Real Estate'),
  ('MAS', 'Masco', 'Industrials'),
  ('IVZ', 'Invesco', 'Financials'),
  ('TRMB', 'Trimble Inc.', 'Information Technology'),
  ('DOC', 'Healthpeak Properties', 'Real Estate'),
  ('WY', 'Weyerhaeuser', 'Real Estate'),
  ('GEN', 'Gen Digital', 'Information Technology'),
  ('TXT', 'Textron', 'Industrials'),
  ('REG', 'Regency Centers', 'Real Estate'),
  ('AIZ', 'Assurant', 'Financials'),
  ('ALLE', 'Allegion', 'Industrials'),
  ('AVY', 'Avery Dennison', 'Materials'),
  ('CHTR', 'Charter Communications', 'Communication Services'),
  ('GL', 'Globe Life', 'Financials'),
  ('HAS', 'Hasbro', 'Consumer Discretionary'),
  ('SWKS', 'Skyworks Solutions', 'Information Technology'),
  ('LII', 'Lennox International', 'Industrials'),
  ('ALB', 'Albemarle Corporation', 'Materials'),
  ('SJM', 'The J.M. Smucker Company', 'Consumer Staples'),
  ('GDDY', 'GoDaddy', 'Information Technology'),
  ('GNRC', 'Generac', 'Industrials'),
  ('BAX', 'Baxter International', 'Health Care'),
  ('IT', 'Gartner', 'Information Technology'),
  ('MKC', 'McCormick & Company', 'Consumer Staples'),
  ('PNW', 'Pinnacle West Capital', 'Utilities'),
  ('TECH', 'Bio-Techne', 'Health Care'),
  ('DVA', 'DaVita', 'Health Care'),
  ('CSGP', 'CoStar Group', 'Real Estate'),
  ('HRL', 'Hormel Foods', 'Consumer Staples'),
  ('COO', 'The Cooper Companies', 'Health Care'),
  ('DECK', 'Deckers Brands', 'Consumer Discretionary'),
  ('UDR', 'UDR, Inc.', 'Real Estate'),
  ('HII', 'Huntington Ingalls Industries', 'Industrials'),
  ('AES', 'AES Corporation', 'Utilities'),
  ('PSKY', 'Paramount Skydance Corporation', 'Communication Services'),
  ('ALGN', 'Align Technology', 'Health Care'),
  ('UHS', 'Universal Health Services', 'Health Care'),
  ('ERIE', 'Erie Indemnity', 'Financials'),
  ('LULU', 'Lululemon Athletica', 'Consumer Discretionary'),
  ('JKHY', 'Jack Henry & Associates', 'Financials'),
  ('FDS', 'FactSet', 'Financials'),
  ('DPZ', 'Domino''s', 'Consumer Discretionary'),
  ('CLX', 'Clorox', 'Consumer Staples'),
  ('CPT', 'Camden Property Trust', 'Real Estate'),
  ('BXP', 'BXP, Inc.', 'Real Estate'),
  ('HSIC', 'Henry Schein', 'Health Care'),
  ('FRT', 'Federal Realty Investment Trust', 'Real Estate'),
  ('APTV', 'Aptiv', 'Consumer Discretionary'),
  ('PODD', 'Insulet Corporation', 'Health Care'),
  ('PNR', 'Pentair', 'Industrials'),
  ('CTVA', 'Corteva', 'Materials'),
  ('ARE', 'Alexandria Real Estate Equities', 'Real Estate'),
  ('WYNN', 'Wynn Resorts', 'Consumer Discretionary'),
  ('MGM', 'MGM Resorts', 'Consumer Discretionary'),
  ('AOS', 'A. O. Smith', 'Industrials'),
  ('MOS', 'The Mosaic Company', 'Materials'),
  ('NCLH', 'Norwegian Cruise Line Holdings', 'Consumer Discretionary')
on conflict (symbol) do update set name = excluded.name, sector = excluded.sector;

-- Mark your own devices so they can be filtered out of real player counts.
alter table players add column if not exists is_owner boolean not null default false;

-- One row per finished game, newest first.
create or replace view submissions with (security_invoker = true) as
select
  m.created_at at time zone 'America/Chicago'                          as played_at_ct,
  m.puzzle_date,
  (m.puzzle_date - date '2026-10-02') + 1                              as puzzle_number,
  coalesce(ac.name, pa.symbol)                                         as answer,
  case when m.solved then cardinality(m.guesses) || '/5' else 'X/5' end as score,
  m.solved,
  cardinality(m.guesses)                                               as guesses_used,
  (select string_agg(coalesce(c.name, g.sym), ' → ' order by g.ord)
     from unnest(m.guesses) with ordinality as g(sym, ord)
     left join companies c on c.symbol = g.sym)                        as guesses,
  case when p.is_owner then 'you' else 'player' end                    as who,
  left(m.player_id::text, 8)                                           as player,
  p.created_at at time zone 'America/Chicago'                          as player_first_seen_ct
from mystery_plays m
join players p on p.id = m.player_id
left join puzzle_answers pa on pa.puzzle_date = m.puzzle_date
left join companies ac on ac.symbol = pa.symbol
order by m.created_at desc;

-- One row per puzzle day. "real" columns leave out your own devices.
create or replace view daily_summary with (security_invoker = true) as
select
  pa.puzzle_date,
  (pa.puzzle_date - date '2026-10-02') + 1                                  as puzzle_number,
  coalesce(c.name, pa.symbol)                                               as answer,
  count(m.player_id)                                                        as games_total,
  count(m.player_id) filter (where not p.is_owner)                          as games_real,
  count(m.player_id) filter (where not p.is_owner and m.solved)             as solved_real,
  round(100.0 * count(*) filter (where not p.is_owner and m.solved)
        / nullif(count(*) filter (where not p.is_owner), 0))                as solve_rate_real_pct,
  round(avg(cardinality(m.guesses)) filter (where not p.is_owner and m.solved), 1) as avg_guesses_when_solved_real
from puzzle_answers pa
left join companies c on c.symbol = pa.symbol
left join mystery_plays m on m.puzzle_date = pa.puzzle_date
left join players p on p.id = m.player_id
group by pa.puzzle_date, c.name, pa.symbol
order by pa.puzzle_date desc;
